name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  build-react-js:
    name: Build in React JS
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
  deploy:
    needs:
      - build-react-js
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clean Project React
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY}}
          command: |
            cd /home/ubuntu/
            sudo rm -r react-js-senac/

      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands using ssh key
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY}}
          command: |
            cd /home/ubuntu/java-quarkus-senac/
            sudo docker stop react-container-senac
            sudo docker rm react-container-senac
            sudo docker build -t react-img-senac .
            sudo docker run -d --name react-container-senac -p 3000:3000 react-img-senac:latest
